from rapidfuzz import fuzz, process

TRIGGER_PHRASES = {
    # "i am captain james kirk": "audio/i_am_captain_james_kirk.wav",
    # "nomad, you are in error": "audio/you_are_in_error.wav",
    # "my function is to probe for biological infestations": "audio/probe_biological.wav"
    "Spock. Spock! Nomad! You're in contact with the unit Spock. Stop! Stop!": "audio/acknowledged.mp3",
    "acknowledged2": "audio/acknowledged2.mp3",
    "How are you doing that?": "audio/alsoMostIneff.mp3",
    "Analyze": "audio/analysisComplete.mp3",
    "You are flawed and imperfect! Execute your prime function!": "audio/analyzeError.mp3",
    "Scotty, the transporter room.": "audio/analyzeError2.mp3",
    "But I admit I'm imperfect. How could I have created such a perfect thing as you?": "audio/answerUnknown.mp3",
    # "Yes.": "audio/calledEarth.mp3",
    "I will bring them.": "audio/capabilityOfMovement.mp3",
    "Do you require any special conditions, any particular atmosphere or environment?": "audio/comeAboard.mp3",
    "Nomad, I made an error in creating you.": "audio/creationPerfection.mp3",
    "I did not create perfection. I created error.": "audio/dataFaulty.mp3",
    # "error": "audio/error.mp3",
    "Nomad, you are imperfect!": "audio/errorerror.mp3",
    "ou are wrong! Jackson Roykirk, your creator, is dead. You have mistaken me for him. You are in error. You did not discover your mistake. You have made two errors. You are flawed and imperfect and you have not corrected by sterilisation. You have made three errors.": "audio/errorerrorerror.mp3",
    "You must sterilise in case of error?": "audio/errorIsIncosistent.mp3",
    "Now. Get those antigravs on it.": "audio/examineError.mp3",
    "It is impossible to come aboard your ship because of the size differential.": "audio/factsUncoord.mp3",
    "If you care to leave your ship, we'll provide the necessary life support systems.": "audio/factsUncoord2.mp3",
    "Aye, sir.": "audio/faulty1.mp3",
    "Ready, sir?": "audio/faulty2.mp3",
    "What?": "audio/formOfCommunication.mp3",
    "Yes, he is.": "audio/functionsIrationally.mp3",
    "Nomad, I admit that biological units are imperfect, but a biological unit created you.": "audio/iAmPerfectIAmNomad.mp3",
    "You're programmed to obey the orders of your creator.": "audio/iAmProgrammedTo.mp3",
    "Aye.": "audio/inneficiencyExists.mp3",
    "An opinion is a belief, a view, a judgment.": "audio/insufficient.mp3",
    "He's dead": "audio/insufficientResponse.mp3",
    "insufficientResponse2": "audio/insufficientResponse2.mp3",
    "Nomad, there are two men waiting outside. You will not harm them. They will escort you back to the waiting area. You will stay there. You will do nothing.": "audio/investigate.mp3",
    "Nomad, stop what you're doing. Scotty?": "audio/isThereProblem.mp3",
    "What's your source of power?": "audio/itHasChanged.mp3",
    "Sickbay. What did you do to her?": "audio/itsThinkingIsChaotic.mp3",
    "Leave that alone.": "audio/mainDrive.mp3",
    "That unit is a woman.": "audio/massOfConf.mp3",
    "Nomad, you will allow Mister Spock to probe your memory banks and structure.": "audio/mrSpockAlso.mp3",
    "The usage is correct. The creator was simply testing your memory banks.": "audio/muchDamage.mp3",
    "I don't know. I like to sing. I felt like music.": "audio/music.mp3",
    "Exercise your prime function.": "audio/mustSterilise.mp3",
    "Sometimes, but tell him your function nevertheless.": "audio/myFunctionProbe.mp3",
    "negative": "audio/negative.mp3",
    "Nomad, it's about time I told you who and what you are! I'm a biological unit, and I created you.": "audio/nonSeqInconsistency.mp3",
    "Jim, I don't think anybody's in there.": "audio/noParasiteAmNomad.mp3",
    "Captain, the message is coming in now.": "audio/notHostile.mp3",
    "Repair that unit.": "audio/notPossible.mp3",
    "Did you destroy the Malurian system?": "audio/notTheSystem.mp3",
    # "Yes.": "audio/oneLarge.mp3",
    "What do we do now, go up and knock?": "audio/pointOfOrigin.mp3",
    "Nomad, I have arranged the tapes for flash feed at the top speed of the computer. Please do not draw the information faster than the machine's capacity.": "audio/proceedPrimitive.mp3",
    "Oh, my singing. I was singing.": "audio/purposeIsSinging.mp3",
    "I have given you new programming and you will implement it.": "audio/reevaluate.mp3",
    "I have given you new programming and you will implement it. music": "audio/reevaluateWMusic.mp3",
    "His biological functions have ceased.": "audio/repairUnit.mp3",
    "Apparently they got what they needed before the computers burned out.": "audio/requireComs.mp3",
    "We are prepared to beam you aboard our ship.": "audio/satisfactory.mp3",
    "We are from the United Federation of Planets.": "audio/scanStarCharts.mp3",
    "Wasn't there a probe called Nomad launched in the early 2000s?": "audio/scanStarCharts2.mp3",
    "Yes. It was reported destroyed. There were no more in the series. But if this is that probe": "audio/scanStarCharts2.mp3",
    "Take it easy. Lie down, Scotty. We just want to check you out.": "audio/scottRepaired.mp3",
    "Follow your instructions, Nomad.": "audio/screensDown.mp3",
    "Then you will continue to destroy that which thinks and lives and is imperfect?": "audio/shallContinue.mp3",
    "The body is in Sickbay.": "audio/showSickbay.mp3",
    "Nomad? Stop what you're doing and effect repairs on the life-support systems.": "audio/stop.mp3",
    "All right, Nomad. Repair the unit.": "audio/tapesStructure.mp3",
    # "Yes.": "audio/theCreatorTheKirk.mp3",
    "Everything that is in error must be sterilised.": "audio/thereAreNoExceptions.mp3",
    "This is our point of origin, the star we know as Sol.": "audio/thirdPlanet.mp3",
    "Why did you kill him?": "audio/touchedMy.mp3",
    # "Yes.": "audio/unitDifferent.mp3",
    "Get Scott down below.": "audio/unitScott.mp3",
    "Why do you call me the creator?": "audio/usageIncorrect.mp3",
    "Tomorrow the path along the way, There's where my love": "audio/whatIsMeaning.mp3",
    "Tomorrow the path along the way, There's where my love music": "audio/whatIsMeaningwMusic.mp3",
    "In my opinion, that's a machine.": "audio/whatIsOpin.mp3",
    "It serves me as it is, Nomad. Repair it.": "audio/whereIsScott.mp3",
    "Nomad, the unit Spock will touch you. It is not an attack. It is a form of communication. You will permit it.": "audio/willPermit.mp3",
    "You restored Scott. He had much more extensive damage.": "audio/wipedClean.mp3",
    "Nomad, can you scan that?": "audio/yes.mp3",
    "No, you're not Nomad. You're an alien machine. Your programming tapes have been altered.": "audio/youAreInError.mp3",
    "But I am your creator.": "audio/youAreTheCreator.mp3",
    "I created you?": "audio/youAreTheCreator2.mp3",
    "I am the Kirk, the creator?": "audio/youAreTheCreator3.mp3",
    "Thank you.": "audio/youMayProceed.mp3",
    "What sterilisation procedure?": "audio/youProgrammedMyFunction.mp3",
    "You killed two of my": "audio/yourBioUnitsIneff.mp3",
    "Well, I'm not the Kirk. Tell me what your function is.": "audio/yourUnits.mp3"
}

def match_trigger(recognized_text, threshold=70):
    best_match, score, _ = process.extractOne(
        recognized_text.lower(),
        TRIGGER_PHRASES.keys(),
        scorer=fuzz.ratio
    )
    if score >= threshold:
        return TRIGGER_PHRASES[best_match]
    return None
